'use client';

import AdminNav from '@/components/common/AdminNav';

import { Inter } from 'next/font/google';
import Link from 'next/link';
import {
  AiOutlineDashboard,
  AiOutlineTeam,
  AiOutlineMail,
  AiOutlineContainer,
  AiOutlineContacts,
  AiOutlineFileAdd,
} from 'react-icons/ai';
const navItems = [
  { href: '/admin', Icon: AiOutlineDashboard, label: 'Dashboard' },
  { href: '/admin/posts', Icon: AiOutlineContainer, label: 'Posts' },
  { href: '/admin/users', Icon: AiOutlineTeam, label: 'Users' },
  { href: '/admin/comments', Icon: AiOutlineMail, label: 'Comments' },
  { href: '/admin/contact', Icon: AiOutlineContacts, label: 'Contact' },
];
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminNav navItems={navItems} />
        <div className="flex-1 p-4">{children}</div>
        <Link
          href={'/admin/post/create'}
          className="bg-secondary-dark dark:bg-secondary-light  fixed z-10 right-10 bottom-10 p-3 rounded-full hover:scale-90 shadow-sm transition text-primary dark:text-primary-dark"
        >
          <AiOutlineFileAdd size={24} />
        </Link>
      </body>
    </html>
  );
}
